######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 19 11:27:05 2013
######################################################################

#TEMPLATE = consoleapp
QT -=gui
CONFIG += console
win32 {
  TARGET = ../../../tmp_win_installer/powerdevs/build/uname
}

DEPENDPATH += .
INCLUDEPATH += .
unix {
  QMAKE_POST_LINK=strip $(TARGET)
}

# Input
SOURCES += uname.cpp
